### ISSUE TITLE
Some long error

### ISSUE THREAD

**Issue by fawoorki** [raddacle/HA-addons#1]
Hey when i try to install this addon to my HA raspberry pi its just returning this long error

The command '/bin/sh -c chmod +x /cura/get_release_info.sh && latestCura=$(/cura/get_release_info.sh url) && curaReleaseName=$(/cura/get_release_info.sh name) && curl -sSL ${latestCura} > ${curaReleaseName} && rm -f /cura/releaseInfo.json && chmod +x /cura/${curaReleaseName} && /cura/${curaReleaseName} --appimage-extract && sed -i 's/QT_QPA_PLATFORMTHEME=xdgdesktopportal/QT_QPA_PLATFORMTHEME=gtk3/' /cura/squashfs-root/AppRun && rm /cura/${curaReleaseName} && rm -rf /var/lib/apt/lists/* && apt-get autoclean && groupadd cura && useradd -g cura --create-home --home-dir /share/cura cura && mkdir -p /cura && mkdir -p /prints/ && chown -R cura:cura /cura/ /share/cura/ /prints/ && mkdir -p /share/cura/.config/ && echo "XDG_DOWNLOAD_DIR=\"/prints/\"" >> /share/cura/.config/user-dirs.dirs && echo "file:///prints prints" >> /share/cura/.gtk-bookmarks' returned a non-zero code: 2

can somebody help me with this?

**Comment by raddacle** [comment]
Sorry this addon is broken; I could never get it to work. If you don't have another way to run docker containers, I'd suggest installing the portainer addon and then installing this Cura container https://github.com/linuxserver/docker-cura
